apiVersion: v1
kind: Service

metadata:
  name: todo-service

spec:
  selector:
    app: todo-app
    version: blue # !!! esto es lo que vamos a switchear cuando queramos cambiar de versión.

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: NodePort
